### ISSUE TITLE
[Themes] Fonts/text 'look wrong'

### ISSUE THREAD

**Issue by Ads20000** [PlayOnLinux/POL-POM-5#525]
Example
![screenshot from 2017-01-23 17-58-23](https://cloud.githubusercontent.com/assets/3178485/22216110/a698b8d0-e195-11e6-8b1b-a15a012ca262.png)
Ubuntu 16.10

**Comment by plata** [comment]
@qparis I think it's an issue with Roboto light.

**Comment by Ads20000** [comment]
Still applies after `git pull`

**Comment by qparis** [comment]
Seems that the font is too thin for your antialiasing algorithm. Maybe we should try to enlarge it

**Comment by plata** [comment]
@Ads20000 could you play around with the font size and tell us which size you prefer?
Change it in 
`phoenicis-javafx/src/main/resources/org/phoenicis/javafx/themes/unity/descriptionTemplate.html`:
```CSS
body {
    ...
    font-size: 15;
    ...
 }

td.appTitle {
    ...
    font-size: 15;
    ...
}
```

I found 14 or 15 to be a nice size. Might however be to big on Full HD.
